### ISSUE TITLE
Read Summary

### ISSUE THREAD

**Issue by flamedfury** [library-pals/read-action#182]
Hey Katy,

Last year, I recall that when a book was set to `finished` and the action ran, you would get a nice `read summary` with the years stats at the bottom of the workflow run. 

I was just looking out for this and noticed it's gone. Could we bring this back?

**Comment by katydecorah** [comment]
Yes!

**Comment by flamedfury** [comment]
Awesome, 🙌 thank you and happy new year!

**Comment by katydecorah** [comment]
🥂
